/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountSettings: typeof import('./src/views/settings/account/AccountSettings.vue')['default']
    AddMarker: typeof import('./src/components/AddMarker.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    ColourSelector: typeof import('./src/components/ColourSelector.vue')['default']
    Disclaimer: typeof import('./src/components/Disclaimer.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    ImageSettings: typeof import('./src/views/settings/ImageSettings.vue')['default']
    InformationMark: typeof import('./src/components/InformationMark.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    ItemDetails: typeof import('./src/components/ItemDetails.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    MonthSelector: typeof import('./src/components/MonthSelector.vue')['default']
    ReferenceImage: typeof import('./src/components/ReferenceImage.vue')['default']
    ReferenceImages: typeof import('./src/components/ReferenceImages.vue')['default']
    ServerHealth: typeof import('./src/components/ServerHealth.vue')['default']
    ServerSelector: typeof import('./src/components/ServerSelector.vue')['default']
    SettingsMenu: typeof import('./src/views/settings/settingsMenu.vue')['default']
    SettingsWrapper: typeof import('./src/views/settings/SettingsWrapper.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
  }
}
