/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddMarker: typeof import('./src/components/AddMarker.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    Disclaimer: typeof import('./src/components/Disclaimer.vue')['default']
    ImageSettings: typeof import('./src/views/settings/ImageSettings.vue')['default']
    ItemDetails: typeof import('./src/components/ItemDetails.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    ServerHealth: typeof import('./src/components/ServerHealth.vue')['default']
    SettingsMenu: typeof import('./src/views/settings/settingsMenu.vue')['default']
    SettingsWrapper: typeof import('./src/views/settings/SettingsWrapper.vue')['default']
    SideMenu: typeof import('./src/components/SideMenu.vue')['default']
  }
}
