version: "3.8"

services:
  forager:
    build: .
    container_name: forager
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - forager:/pb/pb_data
    ports:
      - 8090:8090
    restart: unless-stopped