version: '3'

vars:
  version: 2.0.0

tasks:
  build: 
    deps: [clean, linux32, linux64, windows64, apple, applesilicon]

  clean:
    cmds:
      - rm -rf build
      - rm -rf dist
      - rm -rf db/dist
    run: once

  front:
    deps: [clean]
    cmds:
      - npm run build
      - cp -R dist db/
    run: once

  buildlinux32:
    deps: [front]
    cmds:
      - cd db && CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -o ../build/forager-"{{.version}}"-linux32
      - cd build && zip forager-"{{.version}}"-linux32.zip forager-"{{.version}}"-linux32

  buildlinux64:
    deps: [front]
    cmds:
      - cd db && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../build/forager-"{{.version}}"-linux
      - cd build && zip forager-"{{.version}}"-linux.zip forager-"{{.version}}"-linux

  buildwindows64:
    deps: [front]
    cmds:
      - cd db && GOOS=windows GOARCH=amd64 go build -o ../build/forager-"{{.version}}".exe
      - cd build && zip forager-"{{.version}}"-windows.zip forager-"{{.version}}".exe

  buildapple:
    deps: [front]
    cmds:
      - cd db && GOOS=darwin GOARCH=amd64 go build -o ../build/forager-"{{.version}}"-apple.app
      - cd build && zip forager-"{{.version}}"-apple.zip forager-"{{.version}}"-apple.app

  buildapplesilicon:
    deps: [front]
    cmds:
      - cd db && GOOS=darwin GOARCH=arm64 go build -o ../build/forager-"{{.version}}"-appliesilicon.app
      - cd build && zip forager-"{{.version}}"-appliesilicon.zip forager-"{{.version}}"-appliesilicon.app

  linux32:
    deps: [buildlinux32]
    cmds:
      - cd build && rm -rf forager-"{{.version}}"-linux32

  linux64:
    deps: [buildlinux64]
    cmds:
      - cd build && rm -rf forager-"{{.version}}"-linux
      
  windows64:
    deps: [buildwindows64]
    cmds:
      - cd build && rm -rf forager-"{{.version}}".exe

  apple:
    deps: [buildapple]
    cmds:
      - cd build && rm -rf forager-"{{.version}}"-apple.app
      
  applesilicon:
    deps: [buildapplesilicon]
    cmds:
      - cd build && rm -rf forager-"{{.version}}"-appliesilicon.app